name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
        build:

            runs-on: ubuntu-latest

            services:
              mysql:
                image: mysql:latest
                ports:
                  - 3306:3306
                env:
                  MYSQL_ROOT_PASSWORD: root


            steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: maven
            - name: Build with Maven
              run: mvn -B test --file pom.xml

            -  name: Update dependency graph
               uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6